name: Generate Doxygen Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants permission to push to gh-pages

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen Documentation
        run: |
          doxygen Doxyfile
          ls -R docs/html

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/html  # Make sure entire directory is pushed
          force_orphan: true  # Force clean deployment
