name: Generate Doxygen Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants permission to push to the gh-pages branch

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy Documentation to GitHub Pages
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # Deployment branch
          folder: docs/html  # Folder where Doxygen generates HTML output
          config_file: Doxyfile  # Path to the Doxygen configuration file
          doxygen_version: 1.9.6  # Ensures a stable Doxygen version
